---
title: "Survival_HMW2"
output: html_document
date: "2023-11-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(dplyr)
library(Hmisc)
library(tidyverse)
library(magrittr)
library(survival)
library(survMisc)
library(survminer)
library(ggpubr)
library(table1)
library(ggplot2)
```


```{r}
data <- read.csv('./follic_dfs_cr.csv')
#check for missing observations 
sapply(data, function(x){sum(is.na(x))})
str(data)

#table(data$age, data$dfstat)
quantile(data$age, weight = data$dftime, probs = c(0.25, 0.5, 0.75))

#label all the categories and make a hemoglobin and age group
data %<>% mutate(clinstg = factor(clinstg, levels = c(1, 2), labels = c('Stage I', 'Stage II')), chemo = factor(chemo, levels = c(0, 1), labels = c('No chemotherapy', 'Chemotherapy')))
```


```{r}
#creating age groups with the same number of events
sum(data$dfstat)
sum(data$dfstat)/4 #--> age groups of 81 events each 

sorted_data <- data.frame(stnum = data$stnum, age = data$age, event = data$dfstat)
sorted_data <- sorted_data[order(-sorted_data$event, sorted_data$age), ]
points <- c(sorted_data$age[81], sorted_data$age[162], sorted_data$age[243], sorted_data$age[324])

age_groups <- ifelse(sorted_data$age <= points[1], 1, 
                     ifelse(sorted_data$age <= points[2], 2, 
                            ifelse(sorted_data$age <= points[3], 3, 4)))

sorted_data$age_groups <- age_groups

sorted_data <- sorted_data[order(sorted_data$stnum), ]

data <- merge(data, sorted_data, by = c('stnum', 'age'))

table(data$age_groups, data$event)#more less eqaul groups. This is meaningfull as the same aged people in the same group 

```
```{r}
#label the variables
label(data$age) = "Age at admission"
label(data$hgb) = "Hemoglobin at admission"
label(data$clinstg) = "Clinical stage at admission"
label(data$chemo) = "Use of chemotherapy"
label(data$dftime) = "Disease-free survival time"
label(data$dfstat) = "Event indicator for DFS"
label(data$age_groups) = "Age group at admission"
#label(data$hgb_group) = "Hemoglobin level at admission"


data$dfstat <- as.numeric(data$dfstat)
```


# Functional form of age and hgb 

```{r}
null_model <- coxph(Surv(dftime, dfstat) ~ 1, data = data) #force betas = 0
nullmodel_res_mart <- resid(null_model, type = 'martingale')
par(mfrow = c(1, 2))
plot(data$age, nullmodel_res_mart, ylab = 'Martingale residual', xlab = 'Age', main = 'Age functional form')
lines(lowess(data$age, nullmodel_res_mart, iter = 0, f = 0.5), col = 'red', lwd = 2, lty = 2)
plot(data$hgb, nullmodel_res_mart, ylab = 'Martingale residual', xlab = 'Haemoglobin', main = 'Haemoglobin functional form')
lines(lowess(data$hgb, nullmodel_res_mart, iter = 0, f = 0.5), col = 'red', lwd = 2, lty = 2)

```

# Proportional Hazard Assumptions 

```{r}
full_model <- coxph(Surv(dftime, dfstat) ~ age + hgb + clinstg + chemo, data = data)
fullmodel_scho <- cox.zph(full_model, transform = 'identity')
#plot 
par(mfrow = c(2, 2))
for (i in seq (4) ) {
  plot (fullmodel_scho, df =3, nsmo =40 , se=TRUE , col = " red", var=i)
  lab = paste0 (" Schoenfeld univariate test p: ", round(fullmodel_scho[[1]][,3][ i],3))
  mtext(lab, side=3)
}
```
```{r}
#age is not satisfying the proportional hazard model --> stratify for it 

stra_model <- coxph(Surv(dftime, dfstat) ~ hgb + chemo + clinstg + strata(age_groups), data = data)
stramodel_scho <- cox.zph(stra_model, transform = 'identity')
#plot
par(mfrow = c(2, 2))
for (i in seq (3) ) {
  plot (stramodel_scho, df =3, nsmo =40 , se=TRUE , col = " red", var=i)
  lab = paste0 (" Schoenfeld univariate test p: ", round(stramodel_scho[[1]][,3][ i],3))
  mtext(lab, side=3)
}
```

```{r}
#goodness of fit

stramodel_dev <- residuals(stra_model, type = 'deviance')
stramodel_mart <- residuals(stra_model, type = 'martingale')

#linear combination score (risk score)
stramodel_score <- stra_model$linear.predictors 
par(mfrow = c(1, 2))
plot(stramodel_score, stramodel_mart, ylab = 'Martingale residuals', xlab = 'Risk score')
lines(lowess(stramodel_score, stramodel_mart, iter = 0, f = 0.6), col = 'red', lwd = 2, lty = 2)
plot(stramodel_score, stramodel_dev, ylab = 'Deviance residuals', xlab = 'Risk score')
lines(lowess(stramodel_score, stramodel_dev, iter = 0, f = 0.6), col = 'red', lwd = 2, lty = 2)

```
```{r}
sum(abs(stramodel_dev) > 2)

summary_model <- data.frame(stnum = data$stnum, y = stra_model$y, pred = stra_model$linear.predictors, res = stramodel_dev)

summary_model %>% filter(abs(res) > 2)
```



```{r}
#Paramters estimates 
```

